import { pgTable, text, serial } from "drizzle-orm/pg-core";

export const places = pgTable("places", {
  id: serial("id").primaryKey(),
  objectid: text("objectid").notNull(),
  globalid: text("globalid").notNull(),
  tx_nome: text("tx_nome").notNull(),
  tx_status: text("tx_status").notNull(),
  tx_reg_adm: text("tx_reg_adm"),
  tx_bairro: text("tx_bairro"),
  tx_mesapingpong: text("tx_mesapingpong"),
  tx_parcao: text("tx_parcao"),
  tx_camposociety: text("tx_camposociety"),
  tx_qdpoliesport: text("tx_qdpoliesport"),
  tx_qdvolei: text("tx_qdvolei"),
  tx_pistaskate: text("tx_pistaskate"),
  tx_churrasqueira: text("tx_churrasqueira"),
  tx_playg_madplastica: text("tx_playg_madplastica"),
  tx_banc_madei: text("tx_banc_madei"),
  tx_banc_concr: text("tx_banc_concr"),
  tx_playg_madeira: text("tx_playg_madeira"),
  tx_balanco: text("tx_balanco"),
  tx_balan_aces: text("tx_balan_aces"),
  tx_escorregad: text("tx_escorregad"),
  tx_gangorra: text("tx_gangorra"),
  tx_gira_gira: text("tx_gira_gira"),
  tx_trepa_trepa: text("tx_trepa_trepa"),
  tx_busto: text("tx_busto"),
  tx_coreto: text("tx_coreto"),
  tx_lixeira: text("tx_lixeira"),
  tx_mesa_concreto: text("tx_mesa_concreto"),
  tx_pergula: text("tx_pergula"),
  tx_apar_ginas_mad: text("tx_apar_ginas_mad"),
  tx_aca_terc_idade: text("tx_aca_terc_idade"),
  tx_apa_gina_inox: text("tx_apa_gina_inox"),
  tx_equipamentos: text("tx_equipamentos"),
  tx_paraciclos: text("tx_paraciclos"),
  latitude: text("latitude").notNull(),
  longitude: text("longitude").notNull(),
});
