CREATE TABLE IF NOT EXISTS "places" (
	"id" serial PRIMARY KEY NOT NULL,
	"objectid" text NOT NULL,
	"globalid" text NOT NULL,
	"tx_nome" text NOT NULL,
	"tx_status" text NOT NULL,
	"tx_reg_adm" text,
	"tx_bairro" text,
	"tx_mesapingpong" text,
	"tx_parcao" text,
	"tx_camposociety" text,
	"tx_qdpoliesport" text,
	"tx_qdvolei" text,
	"tx_pistaskate" text,
	"tx_churrasqueira" text,
	"tx_playg_madplastica" text,
	"tx_banc_madei" text,
	"tx_banc_concr" text,
	"tx_playg_madeira" text,
	"tx_balanco" text,
	"tx_balan_aces" text,
	"tx_escorregad" text,
	"tx_gangorra" text,
	"tx_gira_gira" text,
	"tx_trepa_trepa" text,
	"tx_busto" text,
	"tx_coreto" text,
	"tx_lixeira" text,
	"tx_mesa_concreto" text,
	"tx_pergula" text,
	"tx_apar_ginas_mad" text,
	"tx_aca_terc_idade" text,
	"tx_apa_gina_inox" text,
	"tx_equipamentos" text,
	"tx_paraciclos" text,
	"latitude" text NOT NULL,
	"longitude" text NOT NULL
);
